### ISSUE TITLE
is makeSafe missing an (out :- a) constraint?

### ISSUE THREAD

**Issue by peterwicksstringfield** [etorreborre/registry#9]
Should
```haskell
makeSafe :: forall a ins out. (Typeable a, Solvable ins out) => Registry ins out -> a
```
be
```haskell
makeSafe :: forall a ins out. (Typeable a, Solvable ins out, out :- a) => Registry ins out -> a
```
?

Because as it stands I can compile and run `makeSafe @a @'[] @'[]` which bombs out at runtime and that doesn't feel very safe.

**Comment by etorreborre** [comment]
Good catch, thanks! I fixed it in `0.3.3.0`. BTW don't hesitate to ask if you have any question, I've enabled [discussions](https://github.com/etorreborre/registry/discussions/10) for this.
